name: RSLib
version: '${version}'
main: com.github.ipecter.rtuserver.lib.RSLib
description: RSLib - Library Plugin for RSPlugins
api-version: 1.17
authors: [ IPECTER ]
depend: [ CMI, DiscordSRV ]
softdepend: [ PlaceholderAPI, Oraxen, ItemsAdder ]
commands:
  rslib:
permissions:
  rslib.reload:
    default: op
libraries:
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.14.0
  - org.mongodb:bson:4.11.1
  - com.google.code.gson:gson:2.10.1
  - com.google.guava:guava:31.1-jre
  - org.apache.commons:commons-lang3:3.14.0